//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.Integration.Adapters.DynamicCrm.Configuration.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.Integration.Adapters.DynamicCrm.Configuration.Properties.Resou" +
                            "rces", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Exception.
        /// </summary>
        internal static string ActiveDirectoryExceptionCaption {
            get {
                return ResourceManager.GetString("ActiveDirectoryExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory object Guid: {0}.
        /// </summary>
        internal static string ActiveDirectoryObjectGuid {
            get {
                return ResourceManager.GetString("ActiveDirectoryObjectGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add the Microsoft Dynamics CRM Integration User Account &quot;{0}&quot; to the PrivUserGroup or Groups for your Organizations in the &quot;{1}&quot; Domain..
        /// </summary>
        internal static string ActiveInstallDirectoryExceptionMessage {
            get {
                return ResourceManager.GetString("ActiveInstallDirectoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the Microsoft Dynamics CRM Integration User account &quot;{0}&quot; from the PrivUserGroup or Groups for your Organizations in the &quot;{1}&quot; Domain..
        /// </summary>
        internal static string ActiveRemoveDirectoryExceptionMessage {
            get {
                return ResourceManager.GetString("ActiveRemoveDirectoryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure that the Microsoft Dynamics CRM2011 adapter settings have been applied and are correct..
        /// </summary>
        internal static string AdapterNotRegisteredExceptionMessage {
            get {
                return ResourceManager.GetString("AdapterNotRegisteredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred adding {0} to {1}..
        /// </summary>
        internal static string AddingIntegrationKeyError {
            get {
                return ResourceManager.GetString("AddingIntegrationKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the {0} role.
        /// </summary>
        internal static string AddingIsvExtensionPrivilegeExceptionMessage {
            get {
                return ResourceManager.GetString("AddingIsvExtensionPrivilegeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Exception.
        /// </summary>
        internal static string ApplicationExceptionCaption {
            get {
                return ResourceManager.GetString("ApplicationExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BOTH.
        /// </summary>
        internal static string BothOption {
            get {
                return ResourceManager.GetString("BothOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel the CRM Adapter Configuration?.
        /// </summary>
        internal static string CancelConfimationMessage {
            get {
                return ResourceManager.GetString("CancelConfimationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching Windows application for configuration with command line arguments: {0}.
        /// </summary>
        internal static string CommandLineLaunchMessage {
            get {
                return ResourceManager.GetString("CommandLineLaunchMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration Argument: {0} has value: {1}.
        /// </summary>
        internal static string ConfigArgumentValueMessage {
            get {
                return ResourceManager.GetString("ConfigArgumentValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration was canceled by the user..
        /// </summary>
        internal static string ConfigurationCanceledMessage {
            get {
                return ResourceManager.GetString("ConfigurationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished running the CRM Adapter Configuration utility..
        /// </summary>
        internal static string ConfigurationFinishedMessage {
            get {
                return ResourceManager.GetString("ConfigurationFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Co&amp;nfigure.
        /// </summary>
        internal static string ConfigureButtonText {
            get {
                return ResourceManager.GetString("ConfigureButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting CRM organizations ....
        /// </summary>
        internal static string ConnectionLabelGetText {
            get {
                return ResourceManager.GetString("ConnectionLabelGetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not find any organizations..
        /// </summary>
        internal static string ConnectionLabelNoOrgsFoundText {
            get {
                return ResourceManager.GetString("ConnectionLabelNoOrgsFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the organization that you wish to configure: .
        /// </summary>
        internal static string ConnectionLabelSelectText {
            get {
                return ResourceManager.GetString("ConnectionLabelSelectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the CRM 2011 Xrm Client..
        /// </summary>
        internal static string Crm2011ClientCreationExceptionMessage {
            get {
                return ResourceManager.GetString("Crm2011ClientCreationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics CRM 2011 Adapter Configuration.
        /// </summary>
        internal static string CRMAdapterConfigurationCaption {
            get {
                return ResourceManager.GetString("CRMAdapterConfigurationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user {0} must be in the db_datawriter and db_datareader roles in the {1} database on the {2} server.
        /// </summary>
        internal static string CrmDatabaseWriterExceptionMessage {
            get {
                return ResourceManager.GetString("CrmDatabaseWriterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CRM platform threw the following exception:.
        /// </summary>
        internal static string CRMExceptionThrown {
            get {
                return ResourceManager.GetString("CRMExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Version for the &quot;{0}&quot; organization is &quot;{1}&quot;.
        /// </summary>
        internal static string CrmVersionMessage {
            get {
                return ResourceManager.GetString("CrmVersionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not deactivate entity: {0}.
        /// </summary>
        internal static string DeactivationExceptionMessage {
            get {
                return ResourceManager.GetString("DeactivationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the Distinguished Name for the object &quot;{0}&quot; in the &quot;{1}&quot; domain.
        /// </summary>
        internal static string DirectoryEntryExceptionMessage {
            get {
                return ResourceManager.GetString("DirectoryEntryExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://{0}{1}/mscrmservices/2007/ad/crmdiscoveryservice.asmx.
        /// </summary>
        internal static string DiscoveryServiceUrlStub {
            get {
                return ResourceManager.GetString("DiscoveryServiceUrlStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain: {0}.
        /// </summary>
        internal static string DomainName {
            get {
                return ResourceManager.GetString("DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate key.
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried adding duplicate role with Id {0} to the integration user &quot;{0}&quot;..
        /// </summary>
        internal static string DuplicateKeyIntegrationUserMessage {
            get {
                return ResourceManager.GetString("DuplicateKeyIntegrationUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the {0} entity..
        /// </summary>
        internal static string EntityRemovalExceptionMessage {
            get {
                return ResourceManager.GetString("EntityRemovalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ExceptionCaption {
            get {
                return ResourceManager.GetString("ExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception: .
        /// </summary>
        internal static string ExceptionDump {
            get {
                return ResourceManager.GetString("ExceptionDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished activating the {0} adapter..
        /// </summary>
        internal static string FinishedActivatingAdapterMessage {
            get {
                return ResourceManager.GetString("FinishedActivatingAdapterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished adding the ISV Extension Privilege to the {0} role.
        /// </summary>
        internal static string FinishedAddingIsvExtensionPrivilegeMessage {
            get {
                return ResourceManager.GetString("FinishedAddingIsvExtensionPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished adding the &quot;{0}&quot; user to the proper roles.
        /// </summary>
        internal static string FinishedAddingUserToRoleMessage {
            get {
                return ResourceManager.GetString("FinishedAddingUserToRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Finish.
        /// </summary>
        internal static string FinishedButtonText {
            get {
                return ResourceManager.GetString("FinishedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished copying configuration files.
        /// </summary>
        internal static string FinishedCopyingConfigFileMessage {
            get {
                return ResourceManager.GetString("FinishedCopyingConfigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Creating the Dynamics Integration role.
        /// </summary>
        internal static string FinishedCreatingRoleMessage {
            get {
                return ResourceManager.GetString("FinishedCreatingRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished deactivating the existing {0}s.
        /// </summary>
        internal static string FinishedDeactivatingMessage {
            get {
                return ResourceManager.GetString("FinishedDeactivatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} the {1} entity..
        /// </summary>
        internal static string FinishedDeleteEntityMessage {
            get {
                return ResourceManager.GetString("FinishedDeleteEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished deleting directory.
        /// </summary>
        internal static string FinishedDeletingConfigFileMessage {
            get {
                return ResourceManager.GetString("FinishedDeletingConfigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the dynamics_erpsystemuser entity..
        /// </summary>
        internal static string FinishedErpSystemUserMessage {
            get {
                return ResourceManager.GetString("FinishedErpSystemUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished exporting the pre installation customizations..
        /// </summary>
        internal static string FinishedExportingPreInstallationStateMessage {
            get {
                return ResourceManager.GetString("FinishedExportingPreInstallationStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished generating configuration for the &quot;{0}&quot; entity.
        /// </summary>
        internal static string FinishedGeneratingProviderConfiguration {
            get {
                return ResourceManager.GetString("FinishedGeneratingProviderConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found Directory Entry with name &quot;{0}&quot; and an object type of &quot;{1}&quot;.
        /// </summary>
        internal static string FinishedGettingDirectoryEntry {
            get {
                return ResourceManager.GetString("FinishedGettingDirectoryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished granting privileges to the Dynamics Integration role.
        /// </summary>
        internal static string FinishedGrantingPrivilegesMessage {
            get {
                return ResourceManager.GetString("FinishedGrantingPrivilegesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished resetting IIS on {0}.
        /// </summary>
        internal static string FinishedIISResetMessage {
            get {
                return ResourceManager.GetString("FinishedIISResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished importing the {0} customizations..
        /// </summary>
        internal static string FinishedImportingCustomizationsMessage {
            get {
                return ResourceManager.GetString("FinishedImportingCustomizationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} the plugins for the {1} Organization..
        /// </summary>
        internal static string FinishedInstallingPluginsMessage {
            get {
                return ResourceManager.GetString("FinishedInstallingPluginsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} the solution for the {1} Organization..
        /// </summary>
        internal static string FinishedInstallingSolutionMessage {
            get {
                return ResourceManager.GetString("FinishedInstallingSolutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} the customizations for the {1} entity..
        /// </summary>
        internal static string FinishedModifingEntitiesMessage {
            get {
                return ResourceManager.GetString("FinishedModifingEntitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} the updates for the {1} Organization..
        /// </summary>
        internal static string FinishedModifingOrgsMessage {
            get {
                return ResourceManager.GetString("FinishedModifingOrgsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished {0} the privilege updates for the {1} database..
        /// </summary>
        internal static string FinishedPrivilegesMessage {
            get {
                return ResourceManager.GetString("FinishedPrivilegesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished publishing the metadata changes..
        /// </summary>
        internal static string FinishedPublishingMessage {
            get {
                return ResourceManager.GetString("FinishedPublishingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Updating Registry key &apos;{0}&apos;.
        /// </summary>
        internal static string FinishedRegistryUpdateMessage {
            get {
                return ResourceManager.GetString("FinishedRegistryUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished removing the ISV Extension Privilege from the {0} role.
        /// </summary>
        internal static string FinishedRemovingIsvExtensionPrivilegeMessage {
            get {
                return ResourceManager.GetString("FinishedRemovingIsvExtensionPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished removing the {0} privilege from the {1} role.
        /// </summary>
        internal static string FinishedRemovingPrivilegeMessage {
            get {
                return ResourceManager.GetString("FinishedRemovingPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished deleting the Dynamics Integration role.
        /// </summary>
        internal static string FinishedRemovingRoleMessage {
            get {
                return ResourceManager.GetString("FinishedRemovingRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished renaming the existing {0}s.
        /// </summary>
        internal static string FinishedRenamingMessage {
            get {
                return ResourceManager.GetString("FinishedRenamingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished retrieving all entity metadata.
        /// </summary>
        internal static string FinishedRetreivingEntityMetadata {
            get {
                return ResourceManager.GetString("FinishedRetreivingEntityMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting requirement level for account number..
        /// </summary>
        internal static string FinishedSettingAccountNumberRequirementMessage {
            get {
                return ResourceManager.GetString("FinishedSettingAccountNumberRequirementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting requirement level for address 1 name on {0}.
        /// </summary>
        internal static string FinishedSettingAddressRequirementMessage {
            get {
                return ResourceManager.GetString("FinishedSettingAddressRequirementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting product decimal precision..
        /// </summary>
        internal static string FinishedSettingDecimalPrecisionMessage {
            get {
                return ResourceManager.GetString("FinishedSettingDecimalPrecisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting default value for address 2 {0} on {1}.
        /// </summary>
        internal static string FinishedSettingDefaultAddress2ShippingMethodMessage {
            get {
                return ResourceManager.GetString("FinishedSettingDefaultAddress2ShippingMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting Group membership for: {0}.
        /// </summary>
        internal static string FinishedSettingGroupMembershipMessage {
            get {
                return ResourceManager.GetString("FinishedSettingGroupMembershipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished setting the &apos;Is Integration User&apos; and &apos;Access mode&apos; properties on the &quot;{0}&quot; user.
        /// </summary>
        internal static string FinishedSettingUserPropertiesMessage {
            get {
                return ResourceManager.GetString("FinishedSettingUserPropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished updating organization..
        /// </summary>
        internal static string FinishedUpdatingOrganizationMessage {
            get {
                return ResourceManager.GetString("FinishedUpdatingOrganizationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must restart the Microsoft Dynamics CRM web site. Otherwise, the Microsoft Dynamics CRM Configuration Utility configurations will not be activated..
        /// </summary>
        internal static string IISResetExceptionMessage {
            get {
                return ResourceManager.GetString("IISResetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected to import Microsoft Dynamics Adapter customizations. These customizations may overwrite customizations that have already been imported into Microsoft Dynamics CRM. To continue, click OK or click Cancel to change your selection..
        /// </summary>
        internal static string ImportCustomizationsCheckedMsg {
            get {
                return ResourceManager.GetString("ImportCustomizationsCheckedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not selected to import Microsoft Dynamics Adapter customizations. You will not be able to integrate data until these customizations have been imported. To continue, click OK or click Cancel to change your selection..
        /// </summary>
        internal static string ImportCustomizationsNotCheckedMsg {
            get {
                return ResourceManager.GetString("ImportCustomizationsNotCheckedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As part of the uninstall process you can import the CRM customizations that were exported when the CRM Adapter was configured. If you do this, any customizations that have been installed since configuring the CRM Adapter could be lost..
        /// </summary>
        internal static string ImportPreCustomizationsMessage {
            get {
                return ResourceManager.GetString("ImportPreCustomizationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value: {0} which was supplied for the {1} option is not valid..
        /// </summary>
        internal static string InstallationTypeParamterExceptionMessage {
            get {
                return ResourceManager.GetString("InstallationTypeParamterExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished with installation operations..
        /// </summary>
        internal static string InstallCompleteMessage {
            get {
                return ResourceManager.GetString("InstallCompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string InstallingOperationName {
            get {
                return ResourceManager.GetString("InstallingOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSTALL.
        /// </summary>
        internal static string InstallOption {
            get {
                return ResourceManager.GetString("InstallOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify the Domain, User Name, Password, DiscoveryServiceUrl, and Organization Names to install to..
        /// </summary>
        internal static string InstallParamterMessage {
            get {
                return ResourceManager.GetString("InstallParamterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamics Integration.
        /// </summary>
        internal static string IntegrationRoleName {
            get {
                return ResourceManager.GetString("IntegrationRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dynamics integration role already exists.
        /// </summary>
        internal static string IntegrationRoleNameExisits {
            get {
                return ResourceManager.GetString("IntegrationRoleNameExisits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve the CRM 2011 Adapter system user account ID for the {0} user..
        /// </summary>
        internal static string IntegrationUserExceptionMessage {
            get {
                return ResourceManager.GetString("IntegrationUserExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current metadata timestamp is: &quot;{0}&quot;.
        /// </summary>
        internal static string MetadataTimeStamp {
            get {
                return ResourceManager.GetString("MetadataTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Next &gt;.
        /// </summary>
        internal static string NextButtonText {
            get {
                return ResourceManager.GetString("NextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CRM Organization databases were retrieved.
        /// </summary>
        internal static string NoDatabasesFound {
            get {
                return ResourceManager.GetString("NoDatabasesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CRM entities were retrieved.
        /// </summary>
        internal static string NoEntitiesFound {
            get {
                return ResourceManager.GetString("NoEntitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CRM Organizations were found with a database name of &apos;{0}&apos;.
        /// </summary>
        internal static string NoOrgsWithDbNameFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NoOrgsWithDbNameFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Octet stream: {0}.
        /// </summary>
        internal static string OctetStream {
            get {
                return ResourceManager.GetString("OctetStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://{0}{1}/mscrmservices/2007/Passport/crmdiscoveryservice.asmx.
        /// </summary>
        internal static string OnlineDiscoveryServiceUrlStub {
            get {
                return ResourceManager.GetString("OnlineDiscoveryServiceUrlStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base language code for the &quot;{0}&quot; organization is &quot;{1}&quot;.
        /// </summary>
        internal static string OrganizationBaseLanguageMessage {
            get {
                return ResourceManager.GetString("OrganizationBaseLanguageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occurred while attempting to generate the &quot;{0}ObjectProvider.config&quot; file.
        /// </summary>
        internal static string ProviderConfigurationExceptionMessage {
            get {
                return ResourceManager.GetString("ProviderConfigurationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have chosen to configure entities for integration.  This could result in the loss of any customizations you have made to existing Object Provider configuration files..
        /// </summary>
        internal static string ProviderWarningMessage {
            get {
                return ResourceManager.GetString("ProviderWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update the Registry key &apos;{0}&apos;.
        /// </summary>
        internal static string RegistryUpdateExceptionMessage {
            get {
                return ResourceManager.GetString("RegistryUpdateExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the account that the Microsoft Dynamics CRM Adapter used to connect to Microsoft Dynamics CRM during integrations..
        /// </summary>
        internal static string RemoveAccountNameDescription {
            get {
                return ResourceManager.GetString("RemoveAccountNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Remove.
        /// </summary>
        internal static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REMOVE.
        /// </summary>
        internal static string RemoveOption {
            get {
                return ResourceManager.GetString("RemoveOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing.
        /// </summary>
        internal static string RemovingOperationName {
            get {
                return ResourceManager.GetString("RemovingOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not rename entity: {0}.
        /// </summary>
        internal static string RenameExceptionMessage {
            get {
                return ResourceManager.GetString("RenameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to manually import the Microsoft Dynamics CRM 4.0 customizations prior to running the Microsoft Dynamics CRM Configuration utility..
        /// </summary>
        internal static string RoleImportExceptionMessage {
            get {
                return ResourceManager.GetString("RoleImportExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson.
        /// </summary>
        internal static string SalespersonRoleName {
            get {
                return ResourceManager.GetString("SalespersonRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected CRM Organization Databases.
        /// </summary>
        internal static string SelectedCrmDatabasesLabel {
            get {
                return ResourceManager.GetString("SelectedCrmDatabasesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select to Import Pre-Adapter Installation customizations.
        /// </summary>
        internal static string SelectToImportCaption {
            get {
                return ResourceManager.GetString("SelectToImportCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipping import of Microsoft Dynamics CRM Adapter customizations..
        /// </summary>
        internal static string SkippingImportMsg {
            get {
                return ResourceManager.GetString("SkippingImportMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soap Exception.
        /// </summary>
        internal static string SoapExceptionCaption {
            get {
                return ResourceManager.GetString("SoapExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please manually import the Connector for Microsoft Dynamics solution for the {0} organization.
        /// </summary>
        internal static string SolutionImportMessage {
            get {
                return ResourceManager.GetString("SolutionImportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to {0}.
        /// </summary>
        internal static string SqlConnectionExceptionMessage {
            get {
                return ResourceManager.GetString("SqlConnectionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activating the {0} adapter..
        /// </summary>
        internal static string StartActivatingAdapterMessage {
            get {
                return ResourceManager.GetString("StartActivatingAdapterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the ISV Extension Privilege to the {0} role.
        /// </summary>
        internal static string StartAddingIsvExtensionPrivilegeMessage {
            get {
                return ResourceManager.GetString("StartAddingIsvExtensionPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding the &quot;{0}&quot; user to the proper roles.
        /// </summary>
        internal static string StartAddingUserToRoleMessage {
            get {
                return ResourceManager.GetString("StartAddingUserToRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting to copy object provider configuration files to &quot;{0}&quot;.
        /// </summary>
        internal static string StartCopyingConfigFileMessage {
            get {
                return ResourceManager.GetString("StartCopyingConfigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the Dynamics Integration role.
        /// </summary>
        internal static string StartCreatingRoleMessage {
            get {
                return ResourceManager.GetString("StartCreatingRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivating the existing {0}s.
        /// </summary>
        internal static string StartDeactivatingMessage {
            get {
                return ResourceManager.GetString("StartDeactivatingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the {1} entity..
        /// </summary>
        internal static string StartDeleteEntityMessage {
            get {
                return ResourceManager.GetString("StartDeleteEntityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting object provider configuration directory &quot;{0}&quot;.
        /// </summary>
        internal static string StartDeletingConfigFileMessage {
            get {
                return ResourceManager.GetString("StartDeletingConfigFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the dynamics_erpsystemuser entity..
        /// </summary>
        internal static string StartErpSystemUserMessage {
            get {
                return ResourceManager.GetString("StartErpSystemUserMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting the pre-configuration customizations..
        /// </summary>
        internal static string StartExportingPreInstallationStateMessage {
            get {
                return ResourceManager.GetString("StartExportingPreInstallationStateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started generating configuration for the {0} entity.
        /// </summary>
        internal static string StartGeneratingProviderConfiguration {
            get {
                return ResourceManager.GetString("StartGeneratingProviderConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Active Directory entry &quot;{0}&quot; for object type &quot;{1}&quot;.
        /// </summary>
        internal static string StartGettingDirectoryEntry {
            get {
                return ResourceManager.GetString("StartGettingDirectoryEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting privileges to the Dynamics Integration role.
        /// </summary>
        internal static string StartGrantingPrivilegesMessage {
            get {
                return ResourceManager.GetString("StartGrantingPrivilegesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to reset IIS on {0}.
        /// </summary>
        internal static string StartIISResetMessage {
            get {
                return ResourceManager.GetString("StartIISResetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing the {0} solution..
        /// </summary>
        internal static string StartImportingCustomizationsMessage {
            get {
                return ResourceManager.GetString("StartImportingCustomizationsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the plugins for the {1} Organization..
        /// </summary>
        internal static string StartInstallingPluginsMessage {
            get {
                return ResourceManager.GetString("StartInstallingPluginsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the solution for the {1} Organization..
        /// </summary>
        internal static string StartInstallingSolutionMessage {
            get {
                return ResourceManager.GetString("StartInstallingSolutionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartMessage {
            get {
                return ResourceManager.GetString("StartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the customizations for the {1} entity..
        /// </summary>
        internal static string StartModifingEntitiesMessage {
            get {
                return ResourceManager.GetString("StartModifingEntitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the updates for the {1} Organization..
        /// </summary>
        internal static string StartModifingOrgsMessage {
            get {
                return ResourceManager.GetString("StartModifingOrgsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} the privilege updates for the {1} database..
        /// </summary>
        internal static string StartPrivilegesMessage {
            get {
                return ResourceManager.GetString("StartPrivilegesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing the metadata changes ....
        /// </summary>
        internal static string StartPublishingMessage {
            get {
                return ResourceManager.GetString("StartPublishingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Registry key &apos;{0}&apos;.
        /// </summary>
        internal static string StartRegistryUpdateMessage {
            get {
                return ResourceManager.GetString("StartRegistryUpdateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the ISV Extension Privilege from the {0} role.
        /// </summary>
        internal static string StartRemovingIsvExtensionPrivilegeMessage {
            get {
                return ResourceManager.GetString("StartRemovingIsvExtensionPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing the {0} privilege from the {1} role.
        /// </summary>
        internal static string StartRemovingPrivilegeMessage {
            get {
                return ResourceManager.GetString("StartRemovingPrivilegeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the Dynamics Integration role.
        /// </summary>
        internal static string StartRemovingRoleMessage {
            get {
                return ResourceManager.GetString("StartRemovingRoleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming the existing {0}s.
        /// </summary>
        internal static string StartRenamingMessage {
            get {
                return ResourceManager.GetString("StartRenamingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieving all entity metadata.
        /// </summary>
        internal static string StartRetrievingEntityMetadata {
            get {
                return ResourceManager.GetString("StartRetrievingEntityMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting requirement level for account number..
        /// </summary>
        internal static string StartSettingAccountNumberRequirementMessage {
            get {
                return ResourceManager.GetString("StartSettingAccountNumberRequirementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting requirement level for address 1 name on {0}.
        /// </summary>
        internal static string StartSettingAddressRequirementMessage {
            get {
                return ResourceManager.GetString("StartSettingAddressRequirementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting product decimal precision..
        /// </summary>
        internal static string StartSettingDecimalPrecisionMessage {
            get {
                return ResourceManager.GetString("StartSettingDecimalPrecisionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting default value for address 2 {0} on {1}.
        /// </summary>
        internal static string StartSettingDefaultAddress2ShippingMethodMessage {
            get {
                return ResourceManager.GetString("StartSettingDefaultAddress2ShippingMethodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to set Group membership for: {0}.
        /// </summary>
        internal static string StartSettingGroupMembershipMessage {
            get {
                return ResourceManager.GetString("StartSettingGroupMembershipMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting the &apos;Is Integration User&apos; and &apos;Access mode&apos; properties on the &quot;{0}&quot; user.
        /// </summary>
        internal static string StartSettingUserPropertiesMessage {
            get {
                return ResourceManager.GetString("StartSettingUserPropertiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threading Exception.
        /// </summary>
        internal static string ThreadExceptionCaption {
            get {
                return ResourceManager.GetString("ThreadExceptionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled app domain exception caught..
        /// </summary>
        internal static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled thread exception caught. {0}.
        /// </summary>
        internal static string UnhandledThreadExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledThreadExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name: {0}.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When configuring Microsoft Dynamics CRM organizations, the CRM System Administrator and Crm IntegrationUser accounts must be different..
        /// </summary>
        internal static string UserNameMatchExceptionMessage {
            get {
                return ResourceManager.GetString("UserNameMatchExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the systemuser record for the supplied Microsoft Dynamics CRM Integration account: &apos;{0}&apos;.
        /// </summary>
        internal static string UserNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("UserNotFoundExceptionMessage", resourceCulture);
            }
        }
    }
}
