//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Dynamics.Integration.Adapters.DynamicCrm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Dynamics.Integration.Adapters.DynamicCrm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string AccountObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("AccountObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AccountObjectProvider.
        /// </summary>
        internal static string AccountObjectProviderName {
            get {
                return ResourceManager.GetString("AccountObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to add {0}  Exception:   {1}.
        /// </summary>
        internal static string AddingValueExceptionMessage {
            get {
                return ResourceManager.GetString("AddingValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied address integration key property was null or empty.
        /// </summary>
        internal static string AddressIntegrationKeyPropertyInvalidMessage {
            get {
                return ResourceManager.GetString("AddressIntegrationKeyPropertyInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more parameters were null.
        /// </summary>
        internal static string ArgumentNullExceptionMessage {
            get {
                return ResourceManager.GetString("ArgumentNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute &apos;{0}&apos; was not found on entity {1}.  Please verify that the {1} entity contains the {0} attribute..
        /// </summary>
        internal static string AttributeNotFoundOnDynamicEntityExceptionMessage {
            get {
                return ResourceManager.GetString("AttributeNotFoundOnDynamicEntityExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The BinaryComparisonOperator {0} is not supported at this time..
        /// </summary>
        internal static string BinaryComparisonNotSupportedExceptionMessage {
            get {
                return ResourceManager.GetString("BinaryComparisonNotSupportedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binding index was found for the type {0}..
        /// </summary>
        internal static string BindingIndexExceptionMessage {
            get {
                return ResourceManager.GetString("BindingIndexExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the &quot;{0}&quot; certificate in the &quot;{1}&quot; user&apos;s local certificate store..
        /// </summary>
        internal static string CertificateNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("CertificateNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate supplied did not pass required validation..
        /// </summary>
        internal static string CertificateNotValidExceptionMessage {
            get {
                return ResourceManager.GetString("CertificateNotValidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Retrieve Ticket because of a null certificate.
        /// </summary>
        internal static string CertificateNullExceptionMessage {
            get {
                return ResourceManager.GetString("CertificateNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ComplexType for the supplied entity: {0} was not found in the {1}.config file..
        /// </summary>
        internal static string ComplexTypeNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("ComplexTypeNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please run the Microsoft Dynamics CRM Configuration Utility to configure the {0} organization to use the Microsoft Dynamics CRM Adapter.
        /// </summary>
        internal static string ConfiguredOrganizationExceptionMessage {
            get {
                return ResourceManager.GetString("ConfiguredOrganizationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection to the Microsoft Dynamics CRM Discovery Web Service could not be validated using the &quot;{0}&quot; user name and the &quot;{1}&quot; discovery service URL..
        /// </summary>
        internal static string ConnectionValidationExceptionMessage {
            get {
                return ResourceManager.GetString("ConnectionValidationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string ContactObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("ContactObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContactObjectProvider.
        /// </summary>
        internal static string ContactObjectProviderName {
            get {
                return ResourceManager.GetString("ContactObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create price level {0}.
        /// </summary>
        internal static string CreatePriceLevelExceptionMessage {
            get {
                return ResourceManager.GetString("CreatePriceLevelExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a product price level for product {0} on price level {1}.
        /// </summary>
        internal static string CreateProductPriceLevelExceptionMessage {
            get {
                return ResourceManager.GetString("CreateProductPriceLevelExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Dynamics Dynamic CRM.
        /// </summary>
        internal static string CRMAdapterDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicCRM.
        /// </summary>
        internal static string CRMAdapterName {
            get {
                return ResourceManager.GetString("CRMAdapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Microsoft Dynamics CRM.
        /// </summary>
        internal static string CRMAdapterSettingsConfigDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsConfigDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration utility.
        /// </summary>
        internal static string CRMAdapterSettingsConfigDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsConfigDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to the Microsoft Dynamics CRM Discovery Service, this can be found in Dynamics CRM under Settings \ Customizations \ Developer Resources.
        /// </summary>
        internal static string CRMAdapterSettingsDiscoveryServiceUrlDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsDiscoveryServiceUrlDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string CRMAdapterSettingsDiscoveryServiceUrlDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsDiscoveryServiceUrlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain that the Microsoft Dynamics CRM host belongs to (Enter crm.dynamics.com for CRM Online).
        /// </summary>
        internal static string CRMAdapterSettingsDomainDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsDomainDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain .
        /// </summary>
        internal static string CRMAdapterSettingsDomainDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsDomainDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The systemuser systemuserid for the INTEGRATION user for a company in Microsoft Dynamics CRM.
        /// </summary>
        internal static string CRMAdapterSettingsIntegrationUserId {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsIntegrationUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True if the instance of CRM is associated to Office 365.
        /// </summary>
        internal static string CRMAdapterSettingsIsOffice365Desc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsIsOffice365Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office 365 Organization.
        /// </summary>
        internal static string CRMAdapterSettingsIsOffice365DisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsIsOffice365DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        internal static string CRMAdapterSettingsOrganizationDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsOrganizationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft Dynamics CRM Discovery Service Role port (Leave blank for CRM Online).
        /// </summary>
        internal static string CRMAdapterSettingsPortDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsPortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        internal static string CRMAdapterSettingsPortDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsPortDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Microsoft Dynamics CRM Discovery Service Role server name (Enter dev.crm.dynamics.com for CRM Online).
        /// </summary>
        internal static string CRMAdapterSettingsServerNameDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsServerNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discovery Server.
        /// </summary>
        internal static string CRMAdapterSettingsServerNameDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsServerNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Microsoft Dynamics CRM Integration account user name.  This should be a user who is not in the System Administrator role.
        /// </summary>
        internal static string CRMAdapterSettingsUserNameDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsUserNameDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user must be a valid user in Microsoft Dynamics CRM.
        /// </summary>
        internal static string CRMAdapterSettingsUserNameDescription {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsUserNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string CRMAdapterSettingsUserNameDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsUserNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CRMAdapterSettingsUserPasswordDesc {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsUserPasswordDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string CRMAdapterSettingsUserPasswordDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsUserPasswordDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL for the Microsoft Dynamics CRM 2011 Discovery Web Service.  This can be found in Microsoft Dynamics CRM under Settings &gt; Customizations &gt; Developer Resources.
        /// </summary>
        internal static string CRMAdapterSettingsWebServiceUrlDescription {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsWebServiceUrlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string CRMAdapterSettingsWebServiceUrlDisplayName {
            get {
                return ResourceManager.GetString("CRMAdapterSettingsWebServiceUrlDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRM Default.
        /// </summary>
        internal static string CrmDefaultLabel {
            get {
                return ResourceManager.GetString("CrmDefaultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Unit named {0} already exists in the specified Unit Group which may or may not have the same Base Unit.  Microsoft Dynamics CRM does not currently permit Units to have the same name when they belong to the same Unit Group..
        /// </summary>
        internal static string CrmDuplicateUoMExceptionMessage {
            get {
                return ResourceManager.GetString("CrmDuplicateUoMExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Online Host Name).
        /// </summary>
        internal static string CRMOnlineHostName {
            get {
                return ResourceManager.GetString("CRMOnlineHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (On-Line Only).
        /// </summary>
        internal static string CRMOnLineOnly {
            get {
                return ResourceManager.GetString("CRMOnLineOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &quot;{0}&quot; user has not been configured to be the integration user or they do not have their access mode set to &quot;Non-interactive&quot;.
        /// </summary>
        internal static string CrmOnlineUserNotConfiguredExceptionMessage {
            get {
                return ResourceManager.GetString("CrmOnlineUserNotConfiguredExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (On-Premise Only).
        /// </summary>
        internal static string CRMOnPremiseOnly {
            get {
                return ResourceManager.GetString("CRMOnPremiseOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an instance of the Dynamics CRM web service.
        /// </summary>
        internal static string CrmServiceCreationExceptionMessage {
            get {
                return ResourceManager.GetString("CrmServiceCreationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string CurrencyObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("CurrencyObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyObjectProvider.
        /// </summary>
        internal static string CurrencyObjectProviderName {
            get {
                return ResourceManager.GetString("CurrencyObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to retrieve base currency fo the {0} organization.
        /// </summary>
        internal static string CurrencyRetrievalExceptionMessage {
            get {
                return ResourceManager.GetString("CurrencyRetrievalExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an instance of the Dynamics CRM deployment service.
        /// </summary>
        internal static string DeploymentServiceCreationExceptionMessage {
            get {
                return ResourceManager.GetString("DeploymentServiceCreationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dictionary&lt;string, object&gt; supplied contains no entries..
        /// </summary>
        internal static string DictionaryForComplexTypeMappingNotInitializedProperly {
            get {
                return ResourceManager.GetString("DictionaryForComplexTypeMappingNotInitializedProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dictionary&lt;string, object&gt; supplied contains more than one entry..
        /// </summary>
        internal static string DictionaryForKeyNotInitializedProperly {
            get {
                return ResourceManager.GetString("DictionaryForKeyNotInitializedProperly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount List.
        /// </summary>
        internal static string DiscountTypeObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("DiscountTypeObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount List.
        /// </summary>
        internal static string DiscountTypeObjectProviderDisplayName1 {
            get {
                return ResourceManager.GetString("DiscountTypeObjectProviderDisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountTypeObjectProvider.
        /// </summary>
        internal static string DiscountTypeObjectProviderName {
            get {
                return ResourceManager.GetString("DiscountTypeObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an instance of the Dynamics CRM discovery service.
        /// </summary>
        internal static string DiscoveryServiceCreationExceptionMessage {
            get {
                return ResourceManager.GetString("DiscoveryServiceCreationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple {0}s were found meeting the duplicate detection rules..
        /// </summary>
        internal static string DuplicateDetected {
            get {
                return ResourceManager.GetString("DuplicateDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic CRM 2011 Adapter Destination .
        /// </summary>
        internal static string DynamicCRMDestinationAdapterDisplayName {
            get {
                return ResourceManager.GetString("DynamicCRMDestinationAdapterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicCRM2011Destination.
        /// </summary>
        internal static string DynamicCRMDestinationAdapterName {
            get {
                return ResourceManager.GetString("DynamicCRMDestinationAdapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic CRM 2011 Adapter Source.
        /// </summary>
        internal static string DynamicCRMSourceAdapterDisplayName {
            get {
                return ResourceManager.GetString("DynamicCRMSourceAdapterDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicCRM2011Source.
        /// </summary>
        internal static string DynamicCRMSourceAdapterName {
            get {
                return ResourceManager.GetString("DynamicCRMSourceAdapterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        internal static string DynamicObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("DynamicObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicObjectProvider.
        /// </summary>
        internal static string DynamicObjectProviderName {
            get {
                return ResourceManager.GetString("DynamicObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified endpoint version: {0} was not found..
        /// </summary>
        internal static string EndpointVersionNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("EndpointVersionNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CrmReference mapping query returned no results for property: {0} with {1} = {2}..
        /// </summary>
        internal static string EntityReferenceMappingNoResultsExceptionMessage {
            get {
                return ResourceManager.GetString("EntityReferenceMappingNoResultsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CrmReference mapping query returned too many results for property: {0} with {1} = {2}..
        /// </summary>
        internal static string EntityReferenceMappingTooManyResultsExceptionMessage {
            get {
                return ResourceManager.GetString("EntityReferenceMappingTooManyResultsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERP System User.
        /// </summary>
        internal static string ErpSystemUserObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("ErpSystemUserObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErpSystemUserObjectProvider.
        /// </summary>
        internal static string ErpSystemUserObjectProviderName {
            get {
                return ResourceManager.GetString("ErpSystemUserObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The EntityName supplied to GetQueryExpression is null or empty..
        /// </summary>
        internal static string GetQueryExpressionEntityNameExceptionMessage {
            get {
                return ResourceManager.GetString("GetQueryExpressionEntityNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The QueryProperty supplied to GetQueryExpression is null or empty..
        /// </summary>
        internal static string GetQueryExpressionQueryPropertyExceptionMessage {
            get {
                return ResourceManager.GetString("GetQueryExpressionQueryPropertyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ScheduleId supplied to GetUnitQueryExpression is null or empty..
        /// </summary>
        internal static string GetUnitQueryExpressionScheduleIdExceptionMessage {
            get {
                return ResourceManager.GetString("GetUnitQueryExpressionScheduleIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UnitName supplied to GetUnitQueryExpression is null or empty..
        /// </summary>
        internal static string GetUnitQueryExpressionUnitNameExceptionMessage {
            get {
                return ResourceManager.GetString("GetUnitQueryExpressionUnitNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} with id {1} was not found to have a value for it&apos;s dynamics_integrationkey attribute when looking up the {2} property..
        /// </summary>
        internal static string IntegradedEntityLookupNotFound {
            get {
                return ResourceManager.GetString("IntegradedEntityLookupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No {0} was found with a dynamics_integrationkey of {1} for the field {2}..
        /// </summary>
        internal static string IntegradedEntityNotFound {
            get {
                return ResourceManager.GetString("IntegradedEntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Dictionary&lt;string, object&gt; provided does not contain an entry for the &quot;IntegrationKey&quot; key..
        /// </summary>
        internal static string IntegrationKeyEntryMissingFromDictionary {
            get {
                return ResourceManager.GetString("IntegrationKeyEntryMissingFromDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory accounts must be provided in the form :&quot;Domain\User&quot;.
        /// </summary>
        internal static string InvalidADUserName {
            get {
                return ResourceManager.GetString("InvalidADUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Adapter is not of type CRM2011Adapter..
        /// </summary>
        internal static string InvalidCRMAdapterCastException {
            get {
                return ResourceManager.GetString("InvalidCRMAdapterCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to destinationObject is not of type Dictionary&lt;string, object&gt;.
        /// </summary>
        internal static string InvalidDictionaryCastException {
            get {
                return ResourceManager.GetString("InvalidDictionaryCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain cannot be empty or blank.
        /// </summary>
        internal static string InvalidDomainExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidDomainExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied ObjectContainer does not contain an instance of DynamicEntity..
        /// </summary>
        internal static string InvalidEntityCastException {
            get {
                return ResourceManager.GetString("InvalidEntityCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DynamicEntity which was supplied does not have it&apos;s &quot;Name&quot; property set..
        /// </summary>
        internal static string InvalidEntitySupplied {
            get {
                return ResourceManager.GetString("InvalidEntitySupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The global option set {0} was not found on destination organization..
        /// </summary>
        internal static string InvalidGlobalOptionSet {
            get {
                return ResourceManager.GetString("InvalidGlobalOptionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key in not of type CrmService.Key.
        /// </summary>
        internal static string InvalidKeyCastException {
            get {
                return ResourceManager.GetString("InvalidKeyCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Configuration file for the {0} is not present in the {1} directory.&quot;.
        /// </summary>
        internal static string InvalidObjectProviderConfigPath {
            get {
                return ResourceManager.GetString("InvalidObjectProviderConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MappedProperty: {0} which was supplied is not mapped in this provider&apos;s configuration file for the {1} MappedObject&apos;s entry..
        /// </summary>
        internal static string InvalidPropertySupplied {
            get {
                return ResourceManager.GetString("InvalidPropertySupplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The User Name cannot be empty or blank.
        /// </summary>
        internal static string InvalidUserNameExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidUserNameExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string InvoiceObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("InvoiceObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceObjectProvider.
        /// </summary>
        internal static string InvoiceObjectProviderName {
            get {
                return ResourceManager.GetString("InvoiceObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvoiceObjectProvider.
        /// </summary>
        internal static string InvoiceObjectProviderName1 {
            get {
                return ResourceManager.GetString("InvoiceObjectProviderName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d is null or empty..
        /// </summary>
        internal static string KeyForLookupIsNullOrEmpty {
            get {
                return ResourceManager.GetString("KeyForLookupIsNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to contact CRM Metadata Soap Client. Picklist for Entity {0} is not synced  Exception: {1}.
        /// </summary>
        internal static string MetadataClientPicklistExceptionMessage {
            get {
                return ResourceManager.GetString("MetadataClientPicklistExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception while trying to create an instance of the Dynamics CRM metadata service.
        /// </summary>
        internal static string MetadataCreationExceptionMessage {
            get {
                return ResourceManager.GetString("MetadataCreationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple {0} entities were found with the attribute: {1} set to value: {2}..
        /// </summary>
        internal static string MultipleDynamicEntitiesReturnedExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleDynamicEntitiesReturnedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Invoice Details returned..
        /// </summary>
        internal static string MultipleInvoiceDetailsExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleInvoiceDetailsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Order Details returned..
        /// </summary>
        internal static string MultipleOrderDetailsExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleOrderDetailsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple product price levels were found..
        /// </summary>
        internal static string MultipleProductPriceLevelExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleProductPriceLevelExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple products were found with the product number : {0} and the dynamics_integrationkey {0}.
        /// </summary>
        internal static string MultipleProductsReturnedExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleProductsReturnedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Quote Details returned..
        /// </summary>
        internal static string MultipleQuoteDetailsExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleQuoteDetailsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple units were found with the name : {0} and the Unit Group Id: {1}.
        /// </summary>
        internal static string MultipleUoMsReturnedExceptionMessage {
            get {
                return ResourceManager.GetString("MultipleUoMsReturnedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No deleted {0} entities were found with the attribute: {1} set to value: {2}..
        /// </summary>
        internal static string NoDeletedDynamicEntitiesFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NoDeletedDynamicEntitiesFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not add the Substitute or Kit Component because no integrated products were found with the dynamics_integrationkey of: {0}.
        /// </summary>
        internal static string NoIntegratedProductsToAddFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NoIntegratedProductsToAddFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not remove the Substitute or Kit Component because none were found with the dynamics_integrationkey of: {0}.
        /// </summary>
        internal static string NoIntegratedProductsToRemoveFoundExceptionMessage {
            get {
                return ResourceManager.GetString("NoIntegratedProductsToRemoveFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product, {0},  which was supplied on the product price level has not been integrated yet, and must be before price list entries can be created for it..
        /// </summary>
        internal static string NonIntegratedProductExceptionMessage {
            get {
                return ResourceManager.GetString("NonIntegratedProductExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product &apos;{0}&apos; has not been integrated yet, or no longer exists..
        /// </summary>
        internal static string NonIntegratedProductSuppliedExceptionMessage {
            get {
                return ResourceManager.GetString("NonIntegratedProductSuppliedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve any Organizations.
        /// </summary>
        internal static string NoOrganizationsExceptionMessage {
            get {
                return ResourceManager.GetString("NoOrganizationsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ICriterion instance supplied is null.
        /// </summary>
        internal static string NullICriterionExceptionMessage {
            get {
                return ResourceManager.GetString("NullICriterionExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request was null.
        /// </summary>
        internal static string NullRequestExceptionMessage {
            get {
                return ResourceManager.GetString("NullRequestExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectProvider.
        /// </summary>
        internal static string ObjectProviderSuffix {
            get {
                return ResourceManager.GetString("ObjectProviderSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string OrderObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("OrderObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderObjectProvider.
        /// </summary>
        internal static string OrderObjectProviderName {
            get {
                return ResourceManager.GetString("OrderObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified organization: {0} was not found..
        /// </summary>
        internal static string OrganizationNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("OrganizationNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid value was supplied for a required parameter..
        /// </summary>
        internal static string ParamterInvalidExceptionMessage {
            get {
                return ResourceManager.GetString("ParamterInvalidExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter that is required to be non-null was supplied with a null value..
        /// </summary>
        internal static string ParamterNullExceptionMessage {
            get {
                return ResourceManager.GetString("ParamterNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picklist.
        /// </summary>
        internal static string PicklistObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("PicklistObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PicklistObjectProvider.
        /// </summary>
        internal static string PicklistObjectProviderName {
            get {
                return ResourceManager.GetString("PicklistObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: {0} not found in Picklist: {1} on entity: {2}..
        /// </summary>
        internal static string PicklistValueNotFound {
            get {
                return ResourceManager.GetString("PicklistValueNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price List.
        /// </summary>
        internal static string PriceLevelObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("PriceLevelObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceLevelObjectProvider.
        /// </summary>
        internal static string PriceLevelObjectProviderName {
            get {
                return ResourceManager.GetString("PriceLevelObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string ProductObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("ProductObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductObjectProvider.
        /// </summary>
        internal static string ProductObjectProviderName {
            get {
                return ResourceManager.GetString("ProductObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR: Unable to publish CRM metadata Exception: {0}.
        /// </summary>
        internal static string PublishExceptionMessage {
            get {
                return ResourceManager.GetString("PublishExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Metadata Changes to CRM.
        /// </summary>
        internal static string PublishingMessage {
            get {
                return ResourceManager.GetString("PublishingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCEED: Published Metadata Changes to CRM.
        /// </summary>
        internal static string PublishSucceeded {
            get {
                return ResourceManager.GetString("PublishSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query cannot be null or empty..
        /// </summary>
        internal static string QueryNullOrEmptyExceptionMessage {
            get {
                return ResourceManager.GetString("QueryNullOrEmptyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        internal static string QuoteObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("QuoteObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QuoteObjectProvider.
        /// </summary>
        internal static string QuoteObjectProviderName {
            get {
                return ResourceManager.GetString("QuoteObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReadDeletedObjectKeys is not implemented for this object provider..
        /// </summary>
        internal static string ReadDeletedKeysNotImplementedExceptionMessage {
            get {
                return ResourceManager.GetString("ReadDeletedKeysNotImplementedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Unable to rename &quot;{0}&quot;  Exception:   {1}.
        /// </summary>
        internal static string RenamingValueExceptionMessage {
            get {
                return ResourceManager.GetString("RenamingValueExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming &quot;{0}&quot; to &quot;{1}&quot;.
        /// </summary>
        internal static string RenamingValueMessage {
            get {
                return ResourceManager.GetString("RenamingValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception occurred while attempting to retrieve all companies: {0}.
        /// </summary>
        internal static string RetrieveAllCompaniesExceptionMessage {
            get {
                return ResourceManager.GetString("RetrieveAllCompaniesExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following exception occurred while attempting to retrieve the &quot;{0}&quot; configured company: {1}.
        /// </summary>
        internal static string RetrieveConfiguredCompanyExceptionMessage {
            get {
                return ResourceManager.GetString("RetrieveConfiguredCompanyExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a price level with transaction currency {0}.
        /// </summary>
        internal static string RetrievePriceLevelExceptionMessage {
            get {
                return ResourceManager.GetString("RetrievePriceLevelExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a price level with id {0}.
        /// </summary>
        internal static string RetrievePriceLevelIdExceptionMessage {
            get {
                return ResourceManager.GetString("RetrievePriceLevelIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not set..
        /// </summary>
        internal static string SettingsErrorMesssage {
            get {
                return ResourceManager.GetString("SettingsErrorMesssage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the object supplied to the ReadObject method is not of type Key or string..
        /// </summary>
        internal static string SuppliedKeyTypeExceptionMessage {
            get {
                return ResourceManager.GetString("SuppliedKeyTypeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property: {0} not supported for Lookup value mapping at this time..
        /// </summary>
        internal static string UnsupportedLookupMappingExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedLookupMappingExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value ({1}) for MappedObject is not supported at this time..
        /// </summary>
        internal static string UnsupportedMappedObjectExceptionMessage {
            get {
                return ResourceManager.GetString("UnsupportedMappedObjectExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string UoMObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("UoMObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoMObjectProvider.
        /// </summary>
        internal static string UoMObjectProviderName {
            get {
                return ResourceManager.GetString("UoMObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoMObjectProvider.
        /// </summary>
        internal static string UoMObjectProviderName1 {
            get {
                return ResourceManager.GetString("UoMObjectProviderName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Group.
        /// </summary>
        internal static string UoMScheduleObjectProviderDisplayName {
            get {
                return ResourceManager.GetString("UoMScheduleObjectProviderDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UoMScheduleObjectProvider.
        /// </summary>
        internal static string UoMScheduleObjectProviderName {
            get {
                return ResourceManager.GetString("UoMScheduleObjectProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} on defaultunitschedule with id &quot;{1}&quot; for product &quot;{2}&quot;.
        /// </summary>
        internal static string UomWithProductAndScheduleIdExceptionMessage {
            get {
                return ResourceManager.GetString("UomWithProductAndScheduleIdExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update a product price level for product {0} on price level {1}.
        /// </summary>
        internal static string UpdateProductPriceLevelExceptionMessage {
            get {
                return ResourceManager.GetString("UpdateProductPriceLevelExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name supplied is not in the format: &quot;Domain\UserName&quot;. You supplied: {0}..
        /// </summary>
        internal static string UserNameFormatExceptionMessage {
            get {
                return ResourceManager.GetString("UserNameFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &quot;{0}&quot; is not enabled in the &quot;{1}&quot; Domain..
        /// </summary>
        internal static string UserNotEnabledInDirectory {
            get {
                return ResourceManager.GetString("UserNotEnabledInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve the system user &quot;{0}&quot;.
        /// </summary>
        internal static string UserNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("UserNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user: &quot;{0}&quot; was not found in the &quot;{1}&quot; Domain..
        /// </summary>
        internal static string UserNotFoundInDirectory {
            get {
                return ResourceManager.GetString("UserNotFoundInDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; is not added because &quot;{0}&quot; already exists.
        /// </summary>
        internal static string ValueExistsMessage {
            get {
                return ResourceManager.GetString("ValueExistsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Windows Identity Foundation installation not found.  See http://www.microsoft.com/download/en/details.aspx?id=17331 for more information.
        /// </summary>
        internal static string WIFInstallationNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("WIFInstallationNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to register the device &quot;{0}&quot; with exception &quot;{1}&quot;.
        /// </summary>
        internal static string WlidDeviceRegistrationExceptionMessage {
            get {
                return ResourceManager.GetString("WlidDeviceRegistrationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve the Federation metadata document at &quot;{0}&quot; with exception: &quot;{1}&quot;.
        /// </summary>
        internal static string WlidFederationMetadataExceptionMessage {
            get {
                return ResourceManager.GetString("WlidFederationMetadataExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a device authorization token for &quot;{0}&quot; with exception: &quot;{1}&quot;.
        /// </summary>
        internal static string WlidTicketDeviceTokenExceptionMessage {
            get {
                return ResourceManager.GetString("WlidTicketDeviceTokenExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve a user authorization token for &quot;{0}&quot; with exception: &quot;{1}&quot;.
        /// </summary>
        internal static string WlidTicketUserTokenExceptionMessage {
            get {
                return ResourceManager.GetString("WlidTicketUserTokenExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve an XmlNode from {0} at &quot;{1}&quot;.
        /// </summary>
        internal static string WlidTicketXpathExceptionMessage {
            get {
                return ResourceManager.GetString("WlidTicketXpathExceptionMessage", resourceCulture);
            }
        }
    }
}
